- name: Create a new user for deployments
  user:
    name: devuser
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Set up SSH key authentication
  authorized_key:
    user: devuser
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH

- name: Install fail2ban for security
  apt:
    name: fail2ban
    state: present
